using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EQ.Domain.Enums
{
    public enum IO_SelfType
    {
        Stop,
        Vacuum,
        Blow
    }

    public enum IO_IN
    {
        //slot 0
        Emergency_Button_Front = 0,
        Emergency_Button_Left = 1,
        Emergency_Button_Rear = 2,
        Emergency_Button_Right = 3,
        Button_Start = 4,
        Button_Stop = 5,
        Button_Reset = 6,
        Motor_Power_On_Check_Signal = 7,
        Not_Defined8 = 8,
        Safety_Power_Box_Smoke_Check_Sensor = 9,
        Safety_Power_Box_Over_Temp_Check_Sensor = 10,
        Safety_Power_Box_Door_Check_Sensor = 11,
        Not_Defined12 = 12,
        Not_Defined13 = 13,
        Not_Defined14 = 14,
        Door_By_Pass_Key_Sw_On_Signal = 15,

        //slot 1
        Main_Air_Check = 16,
        Main_Vaccum_Check_ = 17,
        Not_Defined18 = 18,
        Not_Defined19 = 19,
        Not_Defined20 = 20,
        Not_Defined21 = 21,
        Not_Defined22 = 22,
        Not_Defined23 = 23,
        Safety_InterLock_Unlock_Front_Signal = 24,
        Safety_InterLock_Unlock_Left_L_Signal = 25,
        Safety_InterLock_Unlock_Left_R_Signal = 26,
        Safety_InterLock_Unlock_Rear_Top_Signal = 27,
        Safety_InterLock_Unlock_Rear_L_Signal = 28,
        Safety_InterLock_Unlock_Rear_R_Signal = 29,
        Safety_InterLock_Unlock_Right_L_Signal = 30,
        Safety_InterLock_Unlock_Right_R_Signal = 31,

        //slot 2
        DC_FAN_Power_Box_Left_Top_Fan_Run_Check_Signal = 32,
        DC_FAN_Power_Box_Left_Bottom_Fan_Run_Check_Signal = 33,
        DC_FAN_Power_Box_Right_Top_Fan_Run_Check_Signal = 34,
        DC_FAN_Power_Box_Right_Bottom_Fan_Run_Check_Signal = 35,
        BOTTOM_PC_L_DOOR_FAN = 36,
        BOTTOM_PC_R_DOOR_FAN = 37,
        Not_Defined38 = 38,
        Not_Defined39 = 39,
        DOOR_SW_LEFT_1 = 40,
        DOOR_SW_LEFT_2 = 41,
        DOOR_SW_LEFT_3 = 42,
        DOOR_SW_LEFT_4 = 43,
        DOOR_SW_FRONT_L = 44,
        DOOR_SW_FRONT_R = 45,
        DOOR_SW_RIGHT_L = 46,
        DOOR_SW_RIGHT_R = 47,

        //slot 3
        LOADING_CASSETTE_Cassette_Left_Check_Sensor = 48,
        LOADING_CASSETTE_Cassette_Right_Check_Sensor = 49,
        LOADING_CASSETTE_Cassette_Left_Count_Check_Sensor = 50,
        LOADING_CASSETTE_Cassette_Right_Count_Check_Sensor = 51,
        TRAY_FEEDER_Front_Clamp_ForWard_ON = 52,
        TRAY_FEEDER_Front_Clamp_ForWard_OFF = 53,
        TRAY_FEEDER_Front_Clamp_Up_ON = 54,
        TRAY_FEEDER_Front_Clamp_Up_OFF = 55,
        TRAY_FEEDER_Front_Clamp_Tray_Check_Sensor = 56,
        Not_Defined57 = 57,
        TRAY_FEEDER_Rear_Clamp_ForWard_ON = 58,
        TRAY_FEEDER_Rear_Clamp_ForWard_OFF = 59,
        TRAY_FEEDER_Rear_Clamp_Up_ON = 60,
        TRAY_FEEDER_Rear_Clamp_Up_OFF = 61,
        TRAY_FEEDER_Rear_Clamp_Tray_Check_Sensor = 62,
        Not_Defined63 = 63,

        //slot 4
        TELESCOPIC_HANDLER_Picker_Up_ON = 64,
        TELESCOPIC_HANDLER_Picker_Up_OFF = 65,
        Not_Defined66 = 66,
        Not_Defined67 = 67,
        TELESCOPIC_HANDLER_Picker_Package_Check_Sensor예정 = 68,
        TELESCOPIC_HANDLER_Soket_Clamp_ON = 69,
        TELESCOPIC_HANDLER_Soket_Clamp_OFF = 70,
        TELESCOPIC_HANDLERSoket_Check_Sensor1 = 71,
        TELESCOPIC_HANDLERSoket_Check_Sensor2 = 72,
        Not_Defined73 = 73,
        AUTO_CHART_CHANGE_Casette_Left_Check_Sensor = 74,
        AUTO_CHART_CHANGE_Casette_Right_Check_Sensor = 75,
        AUTO_CHART_CHANGE_Gripper_ChartCount_Check_Sensor = 76,
        AUTO_CHART_CHANGE_Gripper_Clamp_ON = 77,
        AUTO_CHART_CHANGE_Gripper_Forward_ON = 78,
        AUTO_CHART_CHANGE_Gripper_Forward_OFF = 79,

        //slot 5
        AUTO_CHART_CHANGE_Chart_Up_ON = 80,
        AUTO_CHART_CHANGE_Chart_Up_OFF = 81,
        AUTO_CHART_CHANGE_Chart_F_Posion_Check_Sensor = 82,
        AUTO_CHART_CHANGE_Chart_R_Posion_Check_Sensor = 83,
        AUTO_CHART_CHANGE_Gripper_Clamp_OFF = 84, //센서 없음 더미
        STAGE_ELEVATOR_Board_Stage_Heart_Over_Temp_Check_Sensor = 85,
        STAGE_ELEVATOR_Lans_Check_Sensor = 86,
        LOADING_CASSETTE_Tray_Protrude_Check_Sensor = 87,
        CHART_CASSETTE_Chart_Protrude_Check_Sensor = 88,
        INNER_SHUTTER_SHUTTER_Open_ON = 89,
        INNER_SHUTTER_SHUTTER_Open_OFF = 90,
        Not_Defined91 = 91,
        TRAY_FEEDER_Tray_SIDE_PUSHER_ON = 92,
        TRAY_FEEDER_Tray_SIDE_PUSHER_OFF = 93,
        LOADING_CASSETTE_Cassette_Pusher_Forward_ON = 94,
        LOADING_CASSETTE_Cassette_Pusher_Forward_OFF = 95,

        //slot 6
        Not__Defined60,
        Not__Defined61,
        Not__Defined62,
        Not__Defined63,
        Not__Defined64,
        Not__Defined65,
        Not__Defined66,
        Not__Defined67,
        Not__Defined68,
        Not__Defined69,
        Not__Defined6a,
        Not__Defined6b,
        Not__Defined6c,
        Not__Defined6d,
        Not__Defined6e,
        Not__Defined6f,

        //slot 7
        Not__Defined70,
        Not__Defined71,
        Not__Defined72,
        Not__Defined73,
        Not__Defined74,
        Not__Defined75,
        Not__Defined76,
        Not__Defined77,
        Not__Defined78,
        Not__Defined79,
        Not__Defined7a,
        Not__Defined7b,
        Not__Defined7c,
        Not__Defined7d,
        Not__Defined7e,
        Not__Defined7f,

        //slot 8
        Not__Defined80,
        Not__Defined81,
        Not__Defined82,
        Not__Defined83,
        Not__Defined84,
        Not__Defined85,
        Not__Defined86,
        Not__Defined87,
        Not__Defined88,
        Not__Defined89,
        Not__Defined8a,
        Not__Defined8b,
        Not__Defined8c,
        Not__Defined8d,
        Not__Defined8e,
        Not__Defined8f,

        //slot 9
        Not__Defined90,
        Not__Defined91,
        Not__Defined92,
        Not__Defined93,
        Not__Defined94,
        Not__Defined95,
        Not__Defined96,
        Not__Defined97,
        Not__Defined98,
        Not__Defined99,
        Not__Defined9a,
        Not__Defined9b,
        Not__Defined9c,
        Not__Defined9d,
        Not__Defined9e,
        Not__Defined9f,

        //slot 10
        Not__Defined100,
        Not__Defined101,
        Not__Defined102,
        Not__Defined103,
        Not__Defined104,
        Not__Defined105,
        Not__Defined106,
        Not__Defined107,
        Not__Defined108,
        Not__Defined109,
        Not__Defined10a,
        Not__Defined10b,
        Not__Defined10c,
        Not__Defined10d,
        Not__Defined10e,
        Not__Defined10f,
    }

    public enum IO_OUT
    {
        //slot 0
        Button_Start_Lamp = 0,
        Button_Stop_Lamp = 1,
        Button_Reset_Lamp = 2,
        Tower_Lamp_Red = 3,
        Tower_Lamp_Yellow = 4,
        Tower_Lamp_Green = 5,
        BUZZER_1 = 6,
        BUZZER_2 = 7,
        BUZZER_3 = 8,
        Machine_Setting_Light_Off_Signal = 9,
        Door_Open_Motor_Power_BY_Pass_Off_Signal = 10,
        Not_Defined11 = 11,
        Not_Defined12 = 12,
        Not_Defined13 = 13,
        Not_Defined14 = 14,
        Vision_Reset_OnOff_Signal = 15,

        //slot 1
        Safety_InterLock_Unlock_Front_Signal = 16,
        Safety_InterLock_Unlock_Left_L_Signal = 17,
        Safety_InterLock_Unlock_Left_R_Signal = 18,
        Safety_InterLock_Unlock_Rear_Top_Signal = 19,
        Safety_InterLock_Unlock_Rear_L_Signal = 20,
        Safety_InterLock_Unlock_Rear_R_Signal = 21,
        Safety_InterLock_Unlock_Right_L_Signal = 22,
        Safety_InterLock_Unlock_Right_R_Signal = 23,
        Not_Defined24 = 24,
        Not_Defined25 = 25,
        Not_Defined26 = 26,
        Not_Defined27 = 27,
        Not_Defined28 = 28,
        Not_Defined29 = 29,
        Not_Defined30 = 30,
        Not_Defined31 = 31,

        //slot 2
        TRAY_FEEDER_Front_Clamp_ForWard_ON = 32,
        TRAY_FEEDER_Front_Clamp_ForWard_OFF = 33,
        TRAY_FEEDER_Front_Clamp_Up_ON = 34,
        TRAY_FEEDER_Front_Clamp_Up_OFF = 35,
        TRAY_FEEDER_Rear_Clamp_ForWard_ON = 36,
        TRAY_FEEDER_Rear_Clamp_ForWard_OFF = 37,
        TRAY_FEEDER_Rear_Clamp_Up_ON = 38,
        TRAY_FEEDER_Rear_Clamp_Up_OFF = 39,
        TELESCOPIC_HANDLER_Picker_Up_ON = 40,
        TELESCOPIC_HANDLER_Picker_Up_OFF = 41,
        LOADING_CASSETTE_Cassette_Pusher_Forward_ON = 42,
        LOADING_CASSETTE_Cassette_Pusher_Forward_OFF = 43,
        TELESCOPIC_HANDLER_Soket_Clamp_ON = 44,
        TELESCOPIC_HANDLER_Soket_Clamp_OFF = 45,
        AUTO_CHART_CHANGE_Gripper_Clamp_ON = 46,
        AUTO_CHART_CHANGE_Gripper_Clamp_OFF = 47,

        //slot 3
        AUTO_CHART_CHANGE_Chart_Up_ON = 48,
        AUTO_CHART_CHANGE_Chart_Up_OFF = 49,
        INNER_SHUTTER_SHUTTER_Open_ON = 50,
        INNER_SHUTTER_SHUTTER_Open_OFF = 51,
        TRAY_FEEDER_Tray_SIDE_PUSHER_ON = 52,
        TRAY_FEEDER_Tray_SIDE_PUSHER_OFF = 53,
        AUTO_CHART_CHANGE_Gripper_Forward_ON = 54,
        AUTO_CHART_CHANGE_Gripper_Forward_OFF = 55,
        Not_Defined56 = 56,
        Not_Defined57 = 57,
        Not_Defined58 = 58,
        Not_Defined59 = 59,
        Not_Defined60 = 60,
        Not_Defined61 = 61,
        Not_Defined62 = 62,
        Not_Defined63 = 63,

        //slot 4
        Not__Defined40 = 4 * 16,
        Not__Defined41,
        Not__Defined42,
        Not__Defined43,
        Not__Defined44,
        Not__Defined45,
        Not__Defined46,
        Not__Defined47,
        Not__Defined48,
        Not__Defined49,
        Not__Defined4a,
        Not__Defined4b,
        Not__Defined4c,
        Not__Defined4d,
        Not__Defined4e,
        Not__Defined4f,

        //slot 5
        Not__Defined50 = 5 * 16,
        Not__Defined51,
        Not__Defined52,
        Not__Defined53,
        Not__Defined54,
        Not__Defined55,
        Not__Defined56,
        Not__Defined57,
        Not__Defined58,
        Not__Defined59,
        Not__Defined5a,
        Not__Defined5b,
        Not__Defined5c,
        Not__Defined5d,
        Not__Defined5e,
        Not__Defined5f,

        //slot 6
        Not__Defined60 = 6 * 16,
        Not__Defined61,
        Not__Defined62,
        Not__Defined63,
        Not__Defined64,
        Not__Defined65,
        Not__Defined66,
        Not__Defined67,
        Not__Defined68,
        Not__Defined69,
        Not__Defined6a,
        Not__Defined6b,
        Not__Defined6c,
        Not__Defined6d,
        Not__Defined6e,
        Not__Defined6f,

        //slot 7
        Not__Defined70 = 7 * 16,
        Not__Defined71,
        Not__Defined72,
        Not__Defined73,
        Not__Defined74,
        Not__Defined75,
        Not__Defined76,
        Not__Defined77,
        Not__Defined78,
        Not__Defined79,
        Not__Defined7a,
        Not__Defined7b,
        Not__Defined7c,
        Not__Defined7d,
        Not__Defined7e,
        Not__Defined7f,

        //slot 8
        Not__Defined80 = 8 * 16,
        Not__Defined81,
        Not__Defined82,
        Not__Defined83,
        Not__Defined84,
        Not__Defined85,
        Not__Defined86,
        Not__Defined87,
        Not__Defined88,
        Not__Defined89,
        Not__Defined8a,
        Not__Defined8b,
        Not__Defined8c,
        Not__Defined8d,
        Not__Defined8e,
        Not__Defined8f,

        //slot 9
        Not__Defined90 = 9 * 16,
        Not__Defined91,
        Not__Defined92,
        Not__Defined93,
        Not__Defined94,
        Not__Defined95,
        Not__Defined96,
        Not__Defined97,
        Not__Defined98,
        Not__Defined99,
        Not__Defined9a,
        Not__Defined9b,
        Not__Defined9c,
        Not__Defined9d,
        Not__Defined9e,
        Not__Defined9f,

        //slot 10
        Not__Defined100 = 10 * 16,
        Not__Defined101,
        Not__Defined102,
        Not__Defined103,
        Not__Defined104,
        Not__Defined105,
        Not__Defined106,
        Not__Defined107,
        Not__Defined108,
        Not__Defined109,
        Not__Defined10a,
        Not__Defined10b,
        Not__Defined10c,
        Not__Defined10d,
        Not__Defined10e,       
        Not__Defined10f,
    }

    public enum IO_AIN
    {
        // Add Analog Input definitions here
        Analog_Sensor_1 = 0,
        Analog_Sensor_2 = 1,
        Not_Defined2 = 2,
    }

    public enum IO_AOUT
    {
        // Add Analog Output definitions here
        Analog_Out_1 = 0,
        Analog_Out_2 = 1,
        Not_Defined2 = 2,
    }
}
